apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "cluster-api.metadata.name" . }}
  namespace: {{ include "cluster-api.metadata.namespace" . }}
  labels:
    {{- include "cluster-api.metadata.labels" . | indent 4 }}
spec:
  controlPlaneRef:
    apiVersion: {{ .Values.cluster.spec.controlPlaneRef.apiVersion }}
    kind: {{ .Values.cluster.spec.controlPlaneRef.kind }}
    name: {{ .Values.cluster.spec.controlPlaneRef.name | default (include "cluster-api.metadata.name" .) }}
    namespace: {{ .Values.cluster.spec.controlPlaneRef.namespace | default (include "cluster-api.metadata.namespace" .) }}
  infrastructureRef:
    apiVersion: {{ .Values.cluster.spec.infrastructureRef.apiVersion }}
    kind: {{ .Values.cluster.spec.infrastructureRef.kind }}
    name: {{ .Values.cluster.spec.infrastructureRef.name | default (include "cluster-api.metadata.name" .) }}
    namespace: {{ .Values.cluster.spec.infrastructureRef.namespace | default (include "cluster-api.metadata.namespace" .) }}
