global:
  kubernetesVersion: ""
  bootstrap:
    apiVersion: ""
    configTemplateKind: ""
  infrastructure:
    apiVersion: ""
    machineTemplateKind: ""

cluster:
  metadata:
    name: "" # If not specified, Helm release name is used
    namespace: "" # If not specified, Helm release namespace is used

  spec:
    controlPlaneRef:
      apiVersion: ""
      kind: ""
      name: "" # If not specified, "cluster-api.metadata.name" template is used
      namespace: "" # If not specified, "cluster-api.metadata.name" template is used

    infrastructureRef:
      apiVersion: ""
      kind: ""
      name: "" # If not specified, "cluster-api.metadata.name" template is used
      namespace: "" # If not specified, "cluster-api.metadata.name" template is used

machineDeployments: []
